//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionairesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuestionaireScore
    {
        public int QuestionaireId { get; set; }
        public int StudentId { get; set; }
        public bool IsReExamination { get; set; }
        public Nullable<int> ClosedBookScore { get; set; }
        public Nullable<int> OpenBookScore { get; set; }
        public string LimitsScore { get; set; }
        public string BoldfaceScore { get; set; }
        public System.DateTime DateOfScoring { get; set; }
    
        public virtual Questionaire Questionaire { get; set; }
        public virtual Student Student { get; set; }
    }
}
